### ISSUE TITLE
Console “spam”

### ISSUE THREAD

**Issue by riddle** [Celdecea/MusterCull#4]
No idea if it’s intended but I’m getting 

```
00:45:58 [INFO] [MusterCull] Grabbed 0 entities this round.
```

every half a second in console…

Is there any toggle? Or do I need to configure it better so it doesn’t work so fast? I only read [your readme file](https://github.com/Celdecea/MusterCull/blob/master/MusterCull/README). My config is what I copied and pasted from readme.

**Comment by Celdecea** [comment]
Hello, these are debug artifacts. I am so sorry but the only way to hide it
on short notice is to pause damage culling. I am not at my desk but I
believe the command is /mcull pause damage

I won't be able to upload a new version for about 28 hours. I'm without
internet at home or I'd be able to respond quicker, though this will be
resolved soon as well.

Thank you for your patience.

**Comment by riddle** [comment]
It’s fine, don’t worry! I need damage culling to make grinders less effective, and I’ll happilly wait.

**Comment by Celdecea** [comment]
Here is a rebuilt jar without the message.

http://www.mediafire.com/file/ncabz0dmvgnv24r/MusterCull-1.3.1.jar

**Comment by riddle** [comment]
Thank you, you’ve been absolutely great and I feel a bit ashamed that I found another debug artifact… when it damages mobs (edit: or prevents spawn), console is being flooded with

```
00:19:08 [INFO] [MusterCull] Damaging CraftCow at Location{world=CraftWorld{name=world},x=-960.3634360759254,y=4.0,z=160.13807042986986,pitch=0.0,yaw=-238.87315} with 2 point(s).
```

Maybe a configuration node to enable/disable all debug? I’m used to watching console for signs of trouble while I’m working… having all this debug info could prevent me from doing my job.

Sorry for complaining a lot :)

**Comment by Celdecea** [comment]
I'll sit down tonight and come up with a comprehensive solution to this. I
do have another who wishes to keep the debugging information but a config
setting is an easy addition.

**Comment by Celdecea** [comment]
I have added a configuration item but discovered a serious bug in the damage code. I will work on it more over the next 24 hours and try to get a release as soon as possible.

**Comment by riddle** [comment]
Hello, did you manage to add a logging feature/command, so the console stays clean?

**Comment by Celdecea** [comment]
Yes, and thank you for your patience. I have internet fixed at home so this
week I've been catching up.

The console spam was an easy fix but there is a serious bug in how the
plugin treats mobs. It was simple to see what is going on but the nature of
what MusterCull does requires me to do some longer testing (over a couple
of days on a saturated server). As I am aware of it if I were to release it
now and it caused more problems I would feel completely responsible.

Also, thanks to your feedback I've been able to make some improvements.
Please don't feel like you are bugging me at all, my goal is to release a
quality product and the time you take to make your reports is appreciated.

I do apologize for the delays. I'll be back to 100%+ anytime now; doing
this stuff at home is much easier than otherwise.

**Comment by Celdecea** [comment]
Please try [version 1.3.3](http://www.mediafire.com/file/ds8ky4fb1phsc9b/MusterCull-1.3.3.jar). Let me know if there are any more troubles.
